base_settings:
  base_dir: "/work3/s193396"
  version: "v1"
  iteration: 0
  seed: 0

dataset_settings:
  dataset_name: "Dataset001_Heart"
  dataset_id: 1

train_settings:
  network_configuration: "3d_fullres"
  trainer: "nnUNetTrainer_50epochs"
  # trainer: "nnUNetTrainer_250epochs_NoMirroring"
  fold: "all"
  num_processors: 4

data_raw:
  dir: "nnUNet_raw"
  train_images_dir: "imagesTr"
  test_images_dir: "imagesTs"
  train_labels_dir: "labelsTr"
  test_labels_dir: "labelsTs"

data_preprocessed:
  dir: "nnUNet_preprocessed"
  dataset_json: "dataset.json"
  dataset_plans: "nnUNetPlans.json"

data_predicted:
  dir: "nnUNet_predictions"

data_results:
  dir: "nnUNet_results"

data_centerlines:
  dir: "centerlines"

centerline_predictions:
  tolerance: 1.4

connected_components:
  min_size: 30

retraining:
  num_samples_per_retraining: 3
  selection_method: 'worst'