base_settings:
  base_dir: "C:/Users/annae/OneDrive - Danmarks Tekniske Universitet/Speciale/Specialkursus"
  seed: 0

data_loader:
  data_original_dir: "ImageCAS-images"
  data_processed_dir: "ImageCASProcessing"
  data_segmentation_dir: "ImageCAS-TotalSegmentator"
  file_list_dir: "file_list.txt" 
  voxel_spacing: 1

data_processed:
  dataset_dir: "nnUNet_raw/Dataset001_Heart"
  train_images_dir: "imagesTr"
  test_images_dir: "imagesTs"
  train_labels_dir: "labelsTr"
  test_labels_dir: "labelsTs"

segmentation:
  patch_size: 5
  dilation_radius: 5
  sigma: 2
  strictness: 0.5
  ball_size: 2

