base_settings:
  base_dir: /work3/s193396
  seed: 0
  version: experiment_worst_884samples_v3
  num_channels: 1
centerline_predictions:
  tolerance: 1.4
connected_components:
  min_size: 30
data_centerlines:
  dir: centerlines
data_iterations:
  dir: iterations
  results_dir: results
  predictions_dir: predictions
  evaluations_dir: evaluations
data_predicted:
  dir: nnUNet_predictions
data_preprocessed:
  dir: nnUNet_preprocessed
  dataset_json: dataset.json
  dataset_plans: nnUNetPlans.json
data_raw:
  dir: nnUNet_raw
  test_images_dir: imagesTs
  test_labels_dir: labelsTs
  train_images_dir: imagesTr
  train_labels_dir: labelsTr
data_results:
  dir: nnUNet_results
dataset_settings:
  dataset_id: 1
  dataset_name: Dataset001_Heart
home_settings:
  config_dir: conf/config.yaml
  home_dir: /zhome/cd/e/145569
  special_course_dir: Documents/special-course
retraining:
  num_samples_per_retraining: 25
  selection_method: worst
train_settings:
  fold: all
  network_configuration: 3d_fullres
  num_processors: 4
  trainer: nnUNetTrainer_250epochs
  num_samples_initial_training: 5
  finetuning: False
test_settings:
  num_samples_test: 100
