base_settings:
  base_dir: "C:/Users/annae/OneDrive - Danmarks Tekniske Universitet/Speciale/Specialkursus"
  seed: 0

data_loader:
  data_original_dir: "ImageCAS-images"
  data_processed_dir: "ImageCASProcessing"
  data_segmentation_dir: "ImageCAS-TotalSegmentator"
  file_list_dir: "file_lists" 
  file_list_train: "file_list_train.txt"
  file_list_test: "file_list_test.txt"
  voxel_spacing: 1

data_processed:
  dataset_dir: "nnUNet_raw/Dataset001_Heart"
  train_images_dir: "imagesTr"
  test_images_dir: "imagesTs"
  train_labels_dir: "labelsTr"
  test_labels_dir: "labelsTs"

data_predicted:
  dataset_dir: "nnUNet_predictions/Dataset001_Heart"
  date: "11_10_2024"

centerline_predictions:
  dir: "centerline_predictions"
  tolerance: 1

segmentation:
  dilation_radius: 5